Repository SasView/sasview, pull requests merged in 2021-11, with the labels that each got.

#1899 Ticket 1882 coordinate systems
  build_tools/conda_qt5_centos.yml
  build_tools/conda_qt5_min_osx.yml
  build_tools/conda_qt5_min_ubuntu.yml
  build_tools/conda_qt5_osx.yml
  build_tools/conda_qt5_ubuntu.yml
  src/sas/qtgui/Calculators/GenericScatteringCalculator.py
  src/sas/qtgui/Calculators/UI/GenericScatteringCalculator.ui
  src/sas/qtgui/Plotting/Arrow3D.py
  src/sas/sascalc/calculator/sas_gen.py
  test/sascalculator/utest_sas_gen.py
Labels: dependencies

#1933 Doc Update Formats
  .project
  docs/sphinx-docs/source/user/RELEASE.rst
  docs/sphinx-docs/source/user/marketplace.rst
  src/sas/qtgui/Calculators/media/file_converter_help.rst
  src/sas/qtgui/MainWindow/media/data_formats_help.rst
  src/sas/qtgui/Perspectives/Fitting/media/fitting_help.rst
  src/sas/qtgui/Perspectives/Inversion/media/pr_help.rst
  src/sas/sasview/test/convertible_files/LMOG_100254_merged_ISIS2D.txt
  src/sas/sasview/test/media/testdata_help.rst
Labels: SasView Documentation

#1956 Doc Update: P Scaling
  docs/sphinx-docs/source/user/RELEASE.rst
  src/sas/qtgui/Perspectives/Fitting/media/fitting.rst
  src/sas/qtgui/Perspectives/Fitting/media/fitting_help.rst
Labels: SasView Documentation

#1949 Eliminate old tutorial from SasView 5x
  docs/sasview/Tutorial.pdf
  docs/sasview/Tutorial.pptx
  docs/sasview/Tutorial_SV2.pdf
  docs/sasview/Tutorial_SV2.pptx
  docs/sasview/Tutorial_SV3.pdf
  docs/sasview/Tutorial_SV3.pptx
  docs/sphinx-docs/source/user/tutorial.rst
  src/sas/sasview/media/Tutorial.pdf
  src/sas/sasview/media/subtracting_a_model_calculation_from_real_data_v4x.pdf
  src/sas/sasview/media/subtracting_a_model_calculation_from_real_data_v5.pdf
Labels: SasView Documentation

#1938 Doc Update: Polydispersity
  src/sas/qtgui/Perspectives/Fitting/media/enable_pd.png
  src/sas/qtgui/Perspectives/Fitting/media/fitting_help.rst
  src/sas/qtgui/Perspectives/Fitting/media/gpu_options.png
  src/sas/qtgui/Perspectives/Fitting/media/pd_tab.png
Labels: SasView Documentation

#1969 Gh actions artifacts
  .github/workflows/installers.yml
Labels: DiscussAtTheCall
