Repository SasView/sasview, pull requests merged in 2022-07, with the labels that each got.

#2114 Updating developers list for zenodo
  build_tools/release_automation.py
Labels: DiscussAtTheCall

#2065 1992 corfunc perspective needs export and report capabilities
  .github/workflows/installers.yml
  .github/workflows/release.yml
  .gitignore
  build_tools/requirements.txt
  src/sas/qtgui/MainWindow/DataExplorer.py
  src/sas/qtgui/MainWindow/GuiManager.py
  src/sas/qtgui/MainWindow/MainWindow.py
  src/sas/qtgui/MainWindow/UnitTesting/DataExplorerTest.py
  src/sas/qtgui/Perspectives/Corfunc/CorfuncPerspective.py
  src/sas/qtgui/Perspectives/Fitting/FittingLogic.py
  src/sas/qtgui/Perspectives/Fitting/FittingPerspective.py
  src/sas/qtgui/Perspectives/Fitting/ReportPageLogic.py
  src/sas/qtgui/Perspectives/Invariant/InvariantPerspective.py
  src/sas/qtgui/Perspectives/Inversion/InversionPerspective.py
  src/sas/qtgui/Perspectives/perspective.py
  src/sas/qtgui/Plotting/PlotHelper.py
  src/sas/qtgui/Plotting/PlotterBase.py
  src/sas/qtgui/Plotting/UnitTesting/PlotHelperTest.py
  src/sas/qtgui/Utilities/GuiUtils.py
  src/sas/qtgui/Utilities/Reports/ReportDialog.py
  src/sas/qtgui/Utilities/Reports/UI/ReportDialogUI.ui
  src/sas/qtgui/Utilities/Reports/__init__.py
  src/sas/qtgui/Utilities/Reports/report_style.css
  src/sas/qtgui/Utilities/Reports/reportdata.py
  src/sas/qtgui/Utilities/Reports/reports.py
  src/sas/qtgui/Utilities/UnitTesting/ReportDialogTest.py
Labels: Reporting Enhancements, Housekeeping

#2125 2108 display average soft block thickness in corfunc
  src/sas/qtgui/MainWindow/GuiManager.py
  src/sas/qtgui/Perspectives/Corfunc/CorfuncPerspective.py
  src/sas/qtgui/Perspectives/Corfunc/UI/CorfuncPanel.ui
  src/sas/qtgui/Perspectives/Corfunc/corefuncutil.py
  src/sas/sascalc/corfunc/corfunc_calculator.py
  test/corfunc/utest_corfunc.py
Labels: Minor
