Repository SasView/sasview, pull requests merged in 2022-09, with the labels that each got.

#2178 URGENT: Fixed breaking bug in pr_inversion
  src/sas/sascalc/pr/p_invertor.py
Labels: Defect, Critical, Blocker

#2194 Deleted unused sketch of PanDoc implementation
  docs/pandoc-docs/Makefile
  docs/pandoc-docs/build_pandoc.py
  docs/pandoc-docs/source/README.txt
Labels: Minor, Housekeeping

#2197 2196 delete unused files in base directory
  .project
  .pydevproject
  Vagrantfile
  Vagrantprovision.sh
  ez_setup.py
  mac_setup_homebrew.sh
  pytest.ini
Labels: Minor, Housekeeping

#2219 Stop making a new release on every push
  .github/workflows/installers.yml
Labels: Discuss At The Call
