Repository SasView/sasview, pull requests merged in 2022-10, with the labels that each got.

#2233 Move builds to use matplotlib 3.5.x
  .github/workflows/installers.yml
  .github/workflows/release.yml
  build_tools/requirements.txt
  installers/sasview.spec
  setup.py
  src/sas/qtgui/Plotting/Arrow3D.py
  src/sas/qtgui/Plotting/Plotter2D.py
  src/sas/sascalc/simulation/setup.py
  src/sas/sasview/__init__.py
Labels: Discuss At The Call

#2265 Update marketplace urls to https
  docs/sphinx-docs/source/user/RELEASE.rst
  docs/sphinx-docs/source/user/marketplace.rst
Labels: Documentation

#2288 Update rst strings to fix doc build warnings
  docs/sphinx-docs/source/user/working.rst
  src/sas/qtgui/MainWindow/DataManager.py
  src/sas/qtgui/Perspectives/Fitting/media/fitting.rst
  src/sas/qtgui/Perspectives/Fitting/media/fitting_help.rst
  src/sas/qtgui/Plotting/Arrow3D.py
Labels: Documentation

#2309 Fixed file path for log.ini
  src/sas/system/log.py
Labels: Defect, Critical

#2294 2242 quit dont ask me again
  .github/workflows/test.yml
  src/sas/qtgui/MainWindow/GuiManager.py
  src/sas/qtgui/Utilities/HidableDialog.py
  src/sas/system/config/config.py
Labels: Enhancement, Main GUI Window

#2349 Back to explict blacklisting of h5py messages
  src/sas/system/log.ini
Labels: Infrastructure

#2359 Update Optimizer Help Doc
  src/sas/qtgui/Perspectives/Fitting/media/dream-complete.png
  src/sas/qtgui/Perspectives/Fitting/media/dream-incomplete.png
  src/sas/qtgui/Perspectives/Fitting/media/fit-amoeba.png
  src/sas/qtgui/Perspectives/Fitting/media/fit-de.png
  src/sas/qtgui/Perspectives/Fitting/media/fit-dream.png
  src/sas/qtgui/Perspectives/Fitting/media/fit-lm.png
  src/sas/qtgui/Perspectives/Fitting/media/fit-newton.png
  src/sas/qtgui/Perspectives/Fitting/media/optimizer.rst
Labels: Documentation
