Repository SasView/sasview, pull requests merged in 2022-11, with the labels that each got.

#2328 2325 testing needs to be hermetic against user config
  conftest.py
  src/sas/qtgui/Calculators/UnitTesting/GenericScatteringCalculatorTest.py
  src/sas/qtgui/MainWindow/UnitTesting/GuiManagerTest.py
  src/sas/qtgui/MainWindow/UnitTesting/MainWindowTest.py
  src/sas/qtgui/Utilities/Preferences/UnitTesting/PreferencesPanelTest.py
  src/sas/system/config/config_meta.py
Labels: Testing, Infrastructure

#2365 2350: Close the BUMPS/DREAM results panel when data is deleted
  src/sas/qtgui/MainWindow/DataExplorer.py
  src/sas/qtgui/Utilities/ResultPanel.py
Labels: Discuss At The Call

#2357 Fixes in invariant prespective
  src/sas/qtgui/Perspectives/Invariant/UnitTesting/InvariantPerspectiveTest.py
  src/sas/sascalc/invariant/invariant.py
Labels: Discuss At The Call

#2386 Quick fix for issue with 2328
  src/sas/system/config/config_meta.py
Labels: Defect, Critical
