Repository SasView/sasview, pull requests merged in 2023-02, with the labels that each got.

#2420 2419 `setup.py` cleaning
  .github/workflows/ci.yml
  docs/sphinx-docs/build_sphinx.py
  setup.py
  src/sas/qtgui/Utilities/Preferences/UI/__init__.py
  src/sas/qtgui/Utilities/Reports/UI/__init__.py
  src/sas/qtgui/Utilities/UI/__init__.py
  src/sas/qtgui/images/__init__.py
Labels: Infrastructure, Housekeeping

#2394 1763 implement the orientation viewer in 5x and GL Subsystem
  .github/workflows/ci.yml
  build_tools/fix_qt_folder_names_for_codesign.py
  build_tools/requirements.txt
  docs/sphinx-docs/source/dev/gl/opengl.rst
  installers/sasview.spec
  src/sas/qtgui/GL/__init__.py
  src/sas/qtgui/GL/color.py
  src/sas/qtgui/GL/cone.py
  src/sas/qtgui/GL/cube.py
  src/sas/qtgui/GL/cylinder.py
  src/sas/qtgui/GL/icosahedron.py
  src/sas/qtgui/GL/models.py
  src/sas/qtgui/GL/renderable.py
  src/sas/qtgui/GL/scene.py
  src/sas/qtgui/GL/sphere.py
  src/sas/qtgui/GL/surface.py
  src/sas/qtgui/GL/transforms.py
  src/sas/qtgui/GL/visual_checks/primitive_library.py
  src/sas/qtgui/GL/visual_checks/transform_library.py
  src/sas/qtgui/MainWindow/GuiManager.py
  src/sas/qtgui/MainWindow/MainWindow.py
  src/sas/qtgui/Plotting/UnitTesting/AddTextTest.py
  src/sas/qtgui/Utilities/OrientationViewer/OrientationViewer.py
  src/sas/qtgui/Utilities/OrientationViewer/OrientationViewerController.py
  src/sas/qtgui/Utilities/OrientationViewer/UI/OrientationViewerControllerUI.ui
  src/sas/qtgui/Utilities/OrientationViewer/UI/__init__.py
  src/sas/qtgui/Utilities/OrientationViewer/__init__.py
  src/sas/system/log.ini
Labels: Enhancement, Blocker, For Feature Parity, Discuss At The Call

#2430 Tool[s] menu reorganised and renamed
  src/sas/qtgui/MainWindow/UI/MainWindowUI.ui
Labels: Enhancement

#2434 [v5.0.6] Update installer.iss with correct version and copyright dates
  installers/installer.iss
Labels: Discuss At The Call

#2435 Update entitlements.plist
  .github/workflows/release.yml
  build_tools/entitlements.plist
Labels: Discuss At The Call

#2443 Add +/- 1 and 3 sigma lines on residual plots
  src/sas/qtgui/Plotting/Plotter.py
Labels: Discuss At The Call
