Repository SasView/sasview, pull requests merged in 2024-07, with the labels that each got.

#2921 2913 corfunc technical needs attention
  src/sas/qtgui/Perspectives/Corfunc/media/corfunc-technical.rst
Labels: SasView 6.0.0

#2927 Tutorials open in browser to avoid PDF failure
  src/sas/qtgui/MainWindow/GuiManager.py
Labels: Discuss At The Call, SasView 6.0.0

#2894 2885 logos do not appear in about box
  installers/sasview.spec
  src/sas/qtgui/MainWindow/AboutBox.py
  src/sas/qtgui/MainWindow/GuiManager.py
  src/sas/qtgui/MainWindow/UI/AboutUI.ui
  src/sas/qtgui/MainWindow/UI/MainWindowUI.ui
  src/sas/qtgui/MainWindow/UnitTesting/AboutBoxTest.py
  src/sas/qtgui/MainWindow/UnitTesting/GuiManagerTest.py
  src/sas/qtgui/Utilities/About/About.py
  src/sas/qtgui/Utilities/About/__init__.py
  src/sas/qtgui/Utilities/About/images/__init__.py
  src/sas/qtgui/Utilities/About/images/ansto.svg
  src/sas/qtgui/Utilities/About/images/bam.png
  src/sas/qtgui/Utilities/About/images/delft.png
  src/sas/qtgui/Utilities/About/images/diamond.png
  src/sas/qtgui/Utilities/About/images/ess.svg
  src/sas/qtgui/Utilities/About/images/ill.png
  src/sas/qtgui/Utilities/About/images/isis.svg
  src/sas/qtgui/Utilities/About/images/nist.svg
  src/sas/qtgui/Utilities/About/images/ornl.png
  src/sas/qtgui/Utilities/About/images/umd.svg
  src/sas/qtgui/Utilities/About/images/ut.svg
Labels: Discuss At The Call, SasView 6.0.0

#2920 New version of splash screen and icon
  build_tools/requirements.txt
  installers/sasview.spec
  src/sas/qtgui/MainWindow/MainWindow.py
  src/sas/qtgui/Perspectives/Fitting/media/ball.ico
  src/sas/qtgui/UI/res/SVwelcome.png
  src/sas/qtgui/UI/res/ball.ico
  src/sas/qtgui/images/SVwelcome.png
  src/sas/qtgui/images/SVwelcome_mini.png
  src/sas/qtgui/images/ball.icns
  src/sas/qtgui/images/ball.ico
  src/sas/qtgui/images/icons/ball.icns
  src/sas/qtgui/images/icons/ball.ico
  src/sas/system/config/config.py
Labels: SasView 6.0.0

#2925 2909 gpu options help button throws error
  src/sas/qtgui/Perspectives/Fitting/GPUOptions.py
Labels: SasView 6.0.0

#2939 2926 fix broken tutorial links in working with sas view
  docs/sphinx-docs/source/user/tutorial.rst
  docs/sphinx-docs/source/user/working.rst
Labels: Defect, SasView 6.0.0

#2880 2732 fill in whats new boxes for release 6.0.0
  installers/sasview.spec
  src/sas/qtgui/MainWindow/GuiManager.py
  src/sas/qtgui/Perspectives/ParticleEditor/datamodel/calculation.py
  src/sas/qtgui/Perspectives/ParticleEditor/sampling/points.py
  src/sas/qtgui/Utilities/WhatsNew/WhatsNew.py
  src/sas/qtgui/Utilities/WhatsNew/css/__init__.py
  src/sas/qtgui/Utilities/WhatsNew/css/style.css
  src/sas/qtgui/Utilities/WhatsNew/messages/5.0.6/1.html
  src/sas/qtgui/Utilities/WhatsNew/messages/6.0.0/1.html
  src/sas/qtgui/Utilities/WhatsNew/messages/6.0.0/2.html
  src/sas/qtgui/Utilities/WhatsNew/messages/6.0.0/3.html
  src/sas/qtgui/Utilities/WhatsNew/messages/6.0.0/4.html
  src/sas/qtgui/Utilities/WhatsNew/messages/6.0.0/5.html
  src/sas/qtgui/Utilities/WhatsNew/messages/6.0.0/6.html
  src/sas/qtgui/Utilities/WhatsNew/messages/6.0.0/__init__.py
  src/sas/qtgui/Utilities/WhatsNew/messages/6.0.0/box-slicer-center-point.png
  src/sas/qtgui/Utilities/WhatsNew/messages/6.0.0/corfunc-extraction.png
  src/sas/qtgui/Utilities/WhatsNew/messages/6.0.0/corfunc-interaction.png
  src/sas/qtgui/Utilities/WhatsNew/messages/6.0.0/plotting.png
  src/sas/qtgui/Utilities/WhatsNew/messages/6.0.0/preferences.png
  src/sas/qtgui/Utilities/WhatsNew/messages/6.0.0/rhodopsin.png
  src/sas/qtgui/Utilities/WhatsNew/messages/6.0.0/wedge-slicer.png
  src/sas/qtgui/Utilities/WhatsNew/newer.py
Labels: SasView 6.0.0

#2948 2903: Fix for the iPython console in Windows
  installers/sasview.spec
  src/sas/system/log.py
Labels: SasView 6.0.0

#2944 move new pinned dependencies to pinned section.
  build_tools/requirements.txt
Labels: SasView 6.0.0

#2954 2912 moving sliders in corfunc throws errors
  src/sas/qtgui/Perspectives/Corfunc/QSpaceCanvas.py
Labels: SasView 6.0.0

#2959 2669: Default load directory persistence (Redo)
  src/sas/qtgui/Calculators/GenericScatteringCalculator.py
  src/sas/qtgui/Calculators/ResolutionCalculatorPanel.py
  src/sas/qtgui/Calculators/SlitSizeCalculator.py
  src/sas/qtgui/MainWindow/DataExplorer.py
  src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
  src/sas/qtgui/Plotting/SlicerParameters.py
  src/sas/qtgui/Utilities/FileConverter.py
  src/sas/qtgui/Utilities/GridPanel.py
  src/sas/qtgui/Utilities/GuiUtils.py
  src/sas/qtgui/Utilities/Reports/ReportDialog.py
  src/sas/qtgui/Utilities/TabbedModelEditor.py
Labels: SasView 6.0.0

#2899 2898: Installer version
  installers/installer.iss
Labels: SasView 6.0.0

#2955 2798 saving project with the general scattering calculator throws an error
  src/sas/qtgui/Calculators/GenericScatteringCalculator.py
  src/sas/qtgui/Utilities/GuiUtils.py
Labels: SasView 6.0.0

#2950 2910 and 2446: Fixes to auto-restart after preferences change
  src/sas/qtgui/Utilities/Preferences/PreferencesPanel.py
Labels: SasView 6.0.0

#2839 SasData 66: Ensure realistic resolution values loaded from data
  src/sas/qtgui/Perspectives/Fitting/SmearingWidget.py
  src/sas/sascalc/fit/qsmearing.py
Labels: SasView 6.0.0

#2964 Set missing icons
  src/sas/qtgui/MainWindow/Acknowledgements.py
  src/sas/qtgui/Perspectives/Inversion/DMaxExplorerWidget.py
  src/sas/qtgui/Plotting/AddText.py
  src/sas/qtgui/Utilities/About/About.py
  src/sas/qtgui/Utilities/FileConverter.py
  src/sas/qtgui/Utilities/OrientationViewer/OrientationViewer.py
  src/sas/qtgui/Utilities/WhatsNew/WhatsNew.py
Labels: SasView 6.0.0

#2966 2916 gsc plot windows can open hidden - also add GSC plot icon
  src/sas/qtgui/Calculators/GenericScatteringCalculator.py
Labels: SasView 6.0.0

#2862 Pyinstaller part 2
  installers/installer.iss
  installers/sasview.spec
  src/sas/qtgui/Utilities/DocViewWidget.py
  src/sas/sascalc/doc_regen/makedocumentation.py
Labels: SasView 6.0.0

#2977 2976 auxsas has nondeterminstic tests
  test/sascalculator/utest_sas_gen.py
Labels: SasView 6.0.0

#2971 2905 - Orientation Viewer Tool needs a Help Button & Documentation
  src/sas/qtgui/Utilities/OrientationViewer/OrientationViewer.py
Labels: Documentation, SasView 6.0.0

#2969 2831 - fix arrows, stop crashing, fix and improve PDB reading
  src/sas/qtgui/Calculators/GenericScatteringCalculator.py
  src/sas/qtgui/Calculators/UI/GenericScatteringCalculator.ui
  src/sas/qtgui/Calculators/UnitTesting/GenericScatteringCalculatorTest.py
  src/sas/sascalc/calculator/sas_gen.py
Labels: SasView 6.0.0

#2987 2981: Eliminate Errors on Density Panel Calculation
  src/sas/qtgui/Calculators/DensityPanel.py
Labels: SasView 6.0.0

#2992 2990 - Fixed units in scaled plots
  src/sas/qtgui/Utilities/GuiUtils.py
Labels: Discuss At The Call, Bug Fix, SasView 6.0.0

#3000 2999 Fix slow startup time
  src/sas/qtgui/Calculators/GenericScatteringCalculator.py
  src/sas/qtgui/MainWindow/GuiManager.py
Labels: Bug Fix, SasView 6.0.0

#2989 2988: Check if Fit button should be enabled when data is sent to a fit tab
  src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
Labels: Discuss At The Call, SasView 6.0.0
