Repository SasView/sasview, pull requests merged in 2025-06, with the labels that each got.

#3373 Start of the size distribution perspective documentation.
  src/sas/qtgui/Perspectives/SizeDistribution/media/FullFit.png
  src/sas/qtgui/Perspectives/SizeDistribution/media/OptionsTab.png
  src/sas/qtgui/Perspectives/SizeDistribution/media/ParametersTab.png
  src/sas/qtgui/Perspectives/SizeDistribution/media/QuickFit.png
  src/sas/qtgui/Perspectives/SizeDistribution/media/QuickFitFailed.png
  src/sas/qtgui/Perspectives/SizeDistribution/media/backSubtracted.png
  src/sas/qtgui/Perspectives/SizeDistribution/media/sizedistribution_help.rst
  src/sas/sascalc/size_distribution/maxEnt_method.py
  test/size_distribution/data/Alumina_usaxs_irena_diameter_fit.csv
  test/size_distribution/data/Alumina_usaxs_irena_diameter_fitOLD.csv
Labels: Poresize Perspective, SasView 6.1.0

#3434 Updating the size Distribution tests
  src/sas/sascalc/size_distribution/SizeDistribution.py
  test/size_distribution/MaxEntTest.py
  test/size_distribution/data/AluminaUSASX_sasviewSingleShotResults.csv
  test/size_distribution/data/AluminaUSAXS_IrenaTenShotsResults.csv
  test/size_distribution/data/AluminaUSAXS_irenaSingleShotResults.csv
  test/size_distribution/data/AluminaUSAX_sasviewTenShotResults.csv
  test/size_distribution/data/Alumina_usaxs_irena_Iq_fit.csv
  test/size_distribution/data/Alumina_usaxs_irena_diameter_fit.csv
  test/size_distribution/data/Alumina_usaxs_irena_diameter_fitOLD.csv
  test/size_distribution/data/Alumina_usaxs_irena_plot.jpg
  test/size_distribution/data/I_for_dist1.txt
  test/size_distribution/data/InputParametersUsed4AluminaData.csv
  test/size_distribution/data/LMA70_usans
  test/size_distribution/data/LMA70_usans_irena_Iq_fit.csv
  test/size_distribution/data/LMA70_usans_irena_diameter_fit.csv
  test/size_distribution/data/LMA70_usans_irena_input.csv
  test/size_distribution/data/LMA70_usans_irena_plot.jpg
  test/size_distribution/data/alumina_usaxs.dat
  test/size_distribution/data/dist1.txt
Labels: Poresize Perspective, SasView 6.1.0

#3406 3311: Update Shape2SAS UI interactions
  src/sas/qtgui/Calculators/Shape2SAS/Constraints.py
  src/sas/qtgui/Calculators/Shape2SAS/DesignWindow.py
  src/sas/qtgui/Calculators/Shape2SAS/Tables/subunitTable.py
  src/sas/qtgui/Calculators/Shape2SAS/Tables/variableTable.py
  src/sas/qtgui/Calculators/Shape2SAS/UI/DesignWindowUI.ui
  src/sas/qtgui/Calculators/Shape2SAS/genPlugin.py
Labels: SasView 6.1.0

#3446 Shape2SAS outstanding issues redux
  src/sas/qtgui/Calculators/Shape2SAS/Constraints.py
  src/sas/qtgui/Calculators/Shape2SAS/DesignWindow.py
  src/sas/qtgui/Calculators/Shape2SAS/Tables/subunitTable.py
  src/sas/qtgui/Calculators/Shape2SAS/ViewerModel.py
Labels: SasView 6.1.0

#3451 Fix version strings in release-branch builds
  .github/workflows/ci.yml
Labels: Blocker, SasView 6.1.0

#3453 3452 mumag help button doesn't
  src/sas/qtgui/Utilities/MuMag/MuMag.py
Labels: SasView 6.1.0

#3458 Extend pyinstaller data for sas module to include all of sphinx output
  src/sas/__pyinstaller/hook-sas.py
Labels: SasView 6.1.0

#3466 Fix newly appeared SyntaxWarnings
  src/sas/qtgui/Utilities/MuMag/MuMag.py
  src/sas/sascalc/size_distribution/maxEnt_method.py
Labels: SasView 6.1.0

#3459 3457 remove redundant fdr pdfs from 610 before release
  src/sas/qtgui/Perspectives/Corfunc/media/Fibre_Diffraction_Review_2004_12_24.pdf
  src/sas/qtgui/Perspectives/Corfunc/media/Fibre_Diffraction_Review_2005_13_19-22.pdf
  src/sas/qtgui/Perspectives/Corfunc/media/fdr-pdfs.rst
Labels: SasView 6.1.0

#3474 Fixed windows binary signing action
  .github/workflows/ci.yml
Labels: Infrastructure, SasView 6.1.0

#3454 What's New for 6.1.0
  src/sas/qtgui/Utilities/WhatsNew/messages/6.1.0/1.html
  src/sas/qtgui/Utilities/WhatsNew/messages/6.1.0/2.html
  src/sas/qtgui/Utilities/WhatsNew/messages/6.1.0/3.html
  src/sas/qtgui/Utilities/WhatsNew/messages/6.1.0/4.html
  src/sas/qtgui/Utilities/WhatsNew/messages/6.1.0/5.html
  src/sas/qtgui/Utilities/WhatsNew/messages/6.1.0/inversion_tab_batch.png
  src/sas/qtgui/Utilities/WhatsNew/messages/6.1.0/irena_distro.png
  src/sas/qtgui/Utilities/WhatsNew/messages/6.1.0/irena_import.png
  src/sas/qtgui/Utilities/WhatsNew/messages/6.1.0/mumag1.png
  src/sas/qtgui/Utilities/WhatsNew/messages/6.1.0/mumag2.png
  src/sas/qtgui/Utilities/WhatsNew/messages/6.1.0/reparam.png
  src/sas/qtgui/Utilities/WhatsNew/messages/6.1.0/shape2sas.png
Labels: SasView 6.1.0
