Repository SasView/sasview, pull requests merged in 2025-01, with the labels that each got.

#3160 Delete intermediate theory plots by tab id not model id.
  src/sas/qtgui/MainWindow/DataExplorer.py
  src/sas/qtgui/MainWindow/GuiManager.py
  src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
Labels: SasView 6.0.1

#3183 Cherry pick of 3164 for release 6.0.1 - OSX Notarization
  .github/workflows/ci.yml
Labels: SasView 6.0.1

#3181 Removing macOS-13 from the regular build
  .github/workflows/matrix.py
Labels: Discuss At The Call

#3190 Model ID Not Defined
  src/sas/qtgui/MainWindow/DataExplorer.py
Labels: SasView 6.0.1

#3191 Fix calls to set_xticklabels and set_yticklabels
  src/sas/qtgui/Plotting/Plotter.py
Labels: SasView 6.0.1

#3186 2868 call the system default csv viewer not excel
  src/sas/qtgui/Utilities/GridPanel.py
  src/sas/qtgui/Utilities/UI/GridPanelUI.ui
Labels: Discuss At The Call, SasView 6.0.1
