Repository SasView/sasview, pull requests merged in 2025-05, with the labels that each got.

#3330 Documentation viewer/regeneration, wheels, importlib.resources
  docs/sphinx-docs/Makefile
  docs/sphinx-docs/extract-module-resource.py
  run.py
  src/sas/__pyinstaller/hook-sas.py
  src/sas/sascalc/doc_regen/makedocumentation.py
  src/sas/sascalc/doc_regen/regenmodel.py
  src/sas/sascalc/doc_regen/regentoc.py
Labels: SasView 6.1.0

#3333 Update PR and Bug templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull_request_template.md
Labels: SasView 6.1.0

#3361 Q range sliders reset after fitting
  src/sas/qtgui/Plotting/QRangeSlider.py
Labels: Poresize Perspective, SasView 6.1.0

#3358 Pin dependencies for release branches
  .github/workflows/ci.yml
  .github/workflows/matrix.py
  build_tools/requirements-release-macos-latest.txt
  build_tools/requirements-release-ubuntu-22.04.txt
  build_tools/requirements-release-ubuntu-latest.txt
  build_tools/requirements-release-windows-latest.txt
Labels: SasView 6.1.0

#3366 Simultaneous fitting issues
  src/sas/qtgui/Perspectives/Fitting/ComplexConstraint.py
  src/sas/qtgui/Perspectives/Fitting/ConstraintWidget.py
  src/sas/qtgui/Perspectives/Fitting/UnitTesting/ComplexConstraintTest.py
  src/sas/qtgui/Perspectives/Fitting/UnitTesting/ConstraintWidgetTest.py
  src/sas/qtgui/Perspectives/Fitting/UnitTesting/FitPageTest.py
  src/sas/qtgui/Perspectives/Fitting/UnitTesting/FittingWidgetTest.py
  src/sas/sascalc/fit/BumpsFitting.py
Labels: SasView 6.1.0

#3369 removed superfluous line
  src/sas/qtgui/Utilities/ModelEditors/TabbedEditor/TabbedModelEditor.py
Labels: SasView 6.1.0

#3368 Update documentation about building from source
  .gitignore
  INSTALL.md
  INSTALL.txt
  docs/sphinx-docs/source/user/RELEASE.rst
  run.py
  test/README.rst
Labels: Documentation, SasView 6.1.0

#3350 [Sasview v6.1.0] Model editor documentation and template generation fixes
  src/sas/qtgui/Perspectives/Fitting/media/fitting_help.rst
  src/sas/qtgui/Perspectives/Fitting/media/new_model.png
  src/sas/qtgui/Utilities/ModelEditors/TabbedEditor/PluginDefinition.py
  src/sas/qtgui/Utilities/ModelEditors/TabbedEditor/TabbedModelEditor.py
Labels: SasView 6.1.0

#3356 Keep some excess files out of the distribution
  pyproject.toml
Labels: SasView 6.1.0

#3345 3276 parent data needs to be removed from size distribution perspective results plot
  src/sas/qtgui/MainWindow/DataExplorer.py
  src/sas/qtgui/Perspectives/SizeDistribution/SizeDistributionLogic.py
  src/sas/qtgui/Plotting/PlotterData.py
Labels: SasView 6.1.0

#3375 Fix bumps constrained fit
  src/sas/qtgui/Perspectives/Fitting/FittingWidget.py
  src/sas/sascalc/fit/BumpsFitting.py
  src/sas/sascalc/fit/expression.py
Labels: SasView 6.1.0

#3376 Wait to update Size Distribution data plot until user presses Enter
  src/sas/qtgui/Perspectives/SizeDistribution/SizeDistributionPerspective.py
Labels: Poresize Perspective, SasView 6.1.0

#3381 3286: Reparameterization editor documentation
  src/sas/qtgui/MainWindow/UI/MainWindowUI.ui
  src/sas/qtgui/Perspectives/Fitting/media/fitting_help.rst
  src/sas/qtgui/Perspectives/Fitting/media/reparameterization_editor.png
  src/sas/qtgui/Utilities/ModelEditors/ReparamEditor/ReparameterizationEditor.py
Labels: SasView 6.1.0

#3374 3318 saving project fails
  src/sas/qtgui/Perspectives/Inversion/InversionPerspective.py
  src/sas/qtgui/Perspectives/Inversion/NewInversionWidget.py
Labels: SasView 6.1.0

#3389 Fix for documentation window crashes
  src/sas/qtgui/MainWindow/MainWindow.py
Labels: SasView 6.1.0

#3400 Add text boxes to size distribution output box and add/fix units
  src/sas/qtgui/Perspectives/SizeDistribution/SizeDistributionPerspective.py
  src/sas/qtgui/Perspectives/SizeDistribution/UI/SizeDistributionUI.ui
Labels: Poresize Perspective, SasView 6.1.0

#3393 Deduplicate the windows installer artifact
  .github/workflows/ci.yml
Labels: SasView 6.1.0

#3397 Second try at fixing custom labels
  src/sas/qtgui/Plotting/Plotter.py
Labels: SasView 6.1.0

#3403 3378: Ensure python model is selected when window opens
  src/sas/qtgui/Utilities/ModelEditors/TabbedEditor/PluginDefinition.py
Labels: SasView 6.1.0

#3409 3408: Shape2SAS SAXS UI label visibility
  src/sas/qtgui/Calculators/Shape2SAS/UI/DesignWindowUI.ui
Labels: SasView 6.1.0

#3396 3308: Shape2sas documentation
  docs/sphinx-docs/source/user/tools.rst
  src/sas/qtgui/Calculators/Shape2SAS/DesignWindow.py
  src/sas/qtgui/Calculators/media/main_window.png
  src/sas/qtgui/Calculators/media/saxs_virtual_experiment.png
  src/sas/qtgui/Calculators/media/shape_2_sas_help.rst
Labels: SasView 6.1.0

#3402 3309: Shape2SAS plotting enhancements
  src/sas/qtgui/Calculators/Shape2SAS/ViewerModel.py
Labels: SasView 6.1.0

#3424 Power law background estimation in Size Distribution
  src/sas/qtgui/Perspectives/SizeDistribution/SizeDistributionLogic.py
  src/sas/qtgui/Perspectives/SizeDistribution/SizeDistributionPerspective.py
  src/sas/qtgui/Perspectives/SizeDistribution/UI/SizeDistributionUI.ui
  src/sas/sascalc/size_distribution/SizeDistribution.py
Labels: Poresize Perspective, SasView 6.1.0

#3419 Fix error multiplier
  src/sas/sascalc/size_distribution/SizeDistribution.py
Labels: Poresize Perspective, SasView 6.1.0

#3433 3422 default weighting for size distribution should be i if data has no dy
  src/sas/qtgui/Perspectives/SizeDistribution/SizeDistributionLogic.py
  src/sas/qtgui/Perspectives/SizeDistribution/SizeDistributionPerspective.py
Labels: Poresize Perspective, SasView 6.1.0

#3339 Fix mousemove warning in matplotlib plots
  src/sas/qtgui/Plotting/Binder.py
Labels: SasView 6.1.0

#3421 Fix documentation on macOS
  build_tools/code_sign_osx.py
  build_tools/entitlements.plist
Labels: SasView 6.1.0
